import 'package:flutter/material.dart';

class TrainingMenu {
  final String id;
  final String title;
  final String description;
  final String category;
  final String duration;
  final String difficulty;
  final String imagePath; // URL または Assetパス
  final bool isAsset; // trueならImage.asset, falseならImage.network
  final String videoUrl;
  final String overview;
  final List<String> howTo;
  final List<String> tips;
  final String requiredAngle;

  TrainingMenu({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.duration,
    required this.difficulty,
    required this.imagePath,
    this.isAsset = false, // デフォルトはfalse (network)
    required this.videoUrl,
    required this.overview,
    required this.howTo,
    required this.tips,
    required this.requiredAngle,
  });
}

final List<TrainingMenu> DUMMY_TRAININGS = [
  // ===== 5つは Image.network (isAsset: false) =====
  TrainingMenu(
    id: "pushup",
    title: "プッシュアップ",
    description: "10回 | 中級",
    category: "上半身",
    duration: "5分",
    difficulty: "中級",
    imagePath: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=2940&auto=format&fit=crop",
    isAsset: false,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-doing-push-ups-at-the-gym-2287-large.mp4",
    overview: "プッシュアップは、主に大胸筋、上腕三頭筋、三角筋を鍛える自重トレーニングです。体幹の安定性も向上させます。",
    howTo: [
      "四つん這いになり、肩の真下に手を、腰の真下に膝を置きます。",
      "脚をまっすぐ後ろに伸ばし、頭からかかとまでが一直線になるようにします。",
      "息を吸いながら、肘を曲げて胸を床に近づけます。",
      "息を吐きながら、手のひらで床を押し、体を元の位置に戻します。",
    ],
    tips: [
      "常にお腹に力を入れ、腰が反ったり丸まったりしないように意識しましょう。",
      "動作はゆっくりと、筋肉の収縮を意識しながら行いましょう。",
    ],
    requiredAngle: "正面",
  ),
  TrainingMenu(
    id: "yoga",
    title: "モーニングヨガ",
    description: "15分 | 初級",
    category: "ヨガ",
    duration: "15分",
    difficulty: "初級",
    imagePath: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=2787&auto=format&fit=crop",
    isAsset: false,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-doing-yoga-in-the-living-room-12211-large.mp4",
    overview: "朝のヨガは、心と体をリフレッシュさせ、一日を活動的にスタートさせるのに最適です。深い呼吸と共に、全身を優しく伸ばします。",
    howTo: [
      "マットの上に立ち、深く息を吸い込みます。",
      "太陽礼拝のポーズから始めます。",
      "猫と牛のポーズで背骨をほぐします。",
      "最後に瞑想のポーズで呼吸を整えます。",
    ],
    tips: [
      "無理をせず、自分の体の声を聞きましょう。",
      "呼吸を止めないように意識してください。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "squat",
    title: "基本のスクワット",
    description: "15回 | 初級",
    category: "下半身",
    duration: "10分",
    difficulty: "初級",
    imagePath: "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?q=80&w=2940&auto=format&fit=crop",
    isAsset: false,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-squatting-with-weights-42174-large.mp4",
    overview: "スクワットは「キング・オブ・トレーニング」とも呼ばれ、下半身全体と体幹を効率よく鍛えることができます。",
    howTo: [
      "足を肩幅に開きます。",
      "つま先は少し外側に向けます。",
      "椅子に座るようにお尻を後ろに引き、太ももが床と平行になるまで腰を落とします。",
      "かかとに重心を乗せ、ゆっくりと元の位置に戻ります。",
    ],
    tips: [
      "膝がつま先より前に出ないように意識しましょう。",
      "背中が丸まらないように、常に胸を張ってください。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "plank",
    title: "体幹プランク",
    description: "1分 | 初級",
    category: "コア",
    duration: "1分",
    difficulty: "初級",
    imagePath: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?q=80&w=2938&auto=format&fit=crop",
    isAsset: false,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-exercising-on-an-exercise-ball-42175-large.mp4",
    overview: "プランクは、腹筋群、背筋、体幹の深層筋を鍛えるのに非常に効果的なトレーニングです。",
    howTo: [
      "うつ伏せになり、肘を肩の真下に置きます。",
      "前腕とつま先で体を支え、頭からかかとまで一直線にします。",
      "お腹に力を入れ、腰が落ちないように意識します。",
      "その姿勢をキープします。",
    ],
    tips: [
      "お尻が上がりすぎたり、下がりすぎたりしないように注意しましょう。",
      "呼吸は自然に続けてください。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "legraise",
    title: "レッグレイズ",
    description: "15回 x 3セット | 中級",
    category: "コア",
    duration: "10分",
    difficulty: "中級",
    imagePath: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?q=80&w=2787&auto=format&fit=crop",
    isAsset: false,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-doing-leg-raises-on-a-mat-42180-large.mp4",
    overview: "レッグレイズは、特に腹直筋の下部をターゲットにした体幹トレーニングです。",
    howTo: [
      "仰向けになり、手は体の横かお尻の下に置きます。",
      "両足をそろえてまっすぐ伸ばし、床から少し浮かせます。",
      "息を吐きながら、両足を天井に向かってゆっくりと持ち上げます。",
      "息を吸いながら、床すれすれまでゆっくりと下ろします。",
    ],
    tips: [
      "動作中、腰が床から浮かないように常にお腹に力を入れましょう。",
      "足の力ではなく、腹筋の力で足を動かすことを意識してください。",
    ],
    requiredAngle: "側面",
  ),
  
  // ===== 10つは Image.asset (isAsset: true) =====
  TrainingMenu(
    id: "hiit",
    title: "全身HIIT",
    description: "20分 | 中級",
    category: "コア",
    duration: "20分",
    difficulty: "中級",
    imagePath: "assets/images/hiit.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-exercising-in-a-dark-gym-42171-large.mp4",
    overview: "高強度インターバルトレーニング（HIIT）で、短時間で効率よく脂肪を燃焼させ、心肺機能を高めます。",
    howTo: [
      "バーピーを30秒間行います。",
      "10秒間休憩します。",
      "マウンテンクライマーを30秒間行います。",
      "10秒間休憩します。",
      "これを10セット繰り返します。",
    ],
    tips: [
      "全力で動作を行うことが重要です。",
      "休憩時間も正確に守りましょう。",
    ],
    requiredAngle: "正面",
  ),
  TrainingMenu(
    id: "lunge",
    title: "ランジ",
    description: "10回 x 3セット | 初級",
    category: "下半身",
    duration: "10分",
    difficulty: "初級",
    imagePath: "assets/images/lunge.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-doing-lunges-in-a-gym-42172-large.mp4",
    overview: "ランジは、大腿四頭筋、ハムストリングス、大臀筋をターゲットにした下半身トレーニングです。",
    howTo: [
      "まっすぐ立ち、片足を大きく前に踏み出します。",
      "前の膝が90度になるまで体を下げます。後ろの膝は床すれすれまで下ろします。",
      "前の足のかかとで床を押し、元の位置に戻ります。",
      "反対側の足でも同様に行います。",
    ],
    tips: [
      "上半身は常にまっすぐ保ちましょう。",
      "前の膝がつま先より前に出ないように注意してください。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "crunch",
    title: "クランチ",
    description: "20回 x 3セット | 初級",
    category: "コア",
    duration: "5分",
    difficulty: "初級",
    imagePath: "assets/images/crunch.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-doing-crunches-on-a-mat-42170-large.mp4",
    overview: "クランチは、腹直筋（特に上部）を鍛えるための基本的な体幹トレーニングです。",
    howTo: [
      "仰向けになり、膝を90度に曲げます。",
      "手は頭の後ろに軽く添えるか、胸の前で交差させます。",
      "おへそを覗き込むように、肩甲骨が床から浮くまで上半身を持ち上げます。",
      "ゆっくりと元の位置に戻ります。",
    ],
    tips: [
      "首に力を入れすぎず、腹筋の力で起き上がりましょう。",
      "腰が床から浮かないように注意してください。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "pullup",
    title: "懸垂（プルアップ）",
    description: "5回 x 3セット | 上級",
    category: "上半身",
    duration: "15分",
    difficulty: "上級",
    imagePath: "assets/images/pullup.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-doing-pull-ups-42169-large.mp4",
    overview: "懸垂は、広背筋、僧帽筋、上腕二頭筋など、背中と腕の筋肉を鍛える非常に効果的な自重トレーニングです。",
    howTo: [
      "バーを肩幅よりやや広く握ります。",
      "体を持ち上げ、顎がバーの上に来るようにします。",
      "ゆっくりと体を下ろし、腕が完全に伸びるまで下げます。",
      "この動作を繰り返します。",
    ],
    tips: [
      "反動を使わず、筋肉の力で体を持ち上げましょう。",
      "体を下ろす時も力を抜かず、ゆっくりとコントロールします。",
    ],
    requiredAngle: "背面",
  ),
  TrainingMenu(
    id: "downdog",
    title: "ダウンドッグ",
    description: "1分キープ | 初級",
    category: "ヨガ",
    duration: "5分",
    difficulty: "初級",
    imagePath: "assets/images/downdog.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-doing-yoga-in-the-living-room-12211-large.mp4",
    overview: "ダウンドッグ（下向きの犬のポーズ）は、全身を伸ばし、特に背中、ハムストリングス、ふくらはぎの柔軟性を高めます。",
    howTo: [
      "四つん這いになります。",
      "息を吐きながらお尻を持ち上げ、膝と肘を伸ばします。",
      "体全体で三角形を作るイメージです。",
      "かかとを床に近づけようと意識し、深い呼吸を続けます。",
    ],
    tips: [
      "背中が丸まらないように、背筋をまっすぐ伸ばすことを優先しましょう。",
      "膝は無理に伸ばせず、少し曲げても構いません。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "burpee",
    title: "バーピー",
    description: "10回 x 3セット | 上級",
    category: "コア",
    duration: "10分",
    difficulty: "上級",
    imagePath: "assets/images/burpee.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-exercising-in-a-dark-gym-42171-large.mp4",
    overview: "バーピーは、全身の筋力、持久力、心肺機能を同時に鍛えることができる高強度のトレーニングです。",
    howTo: [
      "立った状態からしゃがみ、両手を床につけます。",
      "両足を後ろにジャンプさせ、プランク（腕立て伏せ）の姿勢になります。",
      "（オプション：ここで一度プッシュアップを行います）",
      "両足をジャンプで元の位置に戻します。",
      "立ち上がると同時にジャンプし、頭の上で手を叩きます。",
    ],
    tips: [
      "一連の動作をリズミカルに、流れるように行いましょう。",
      "着地の際は、膝や足首に負担がかからないよう柔らかく着地します。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "benchpress",
    title: "ベンチプレス",
    description: "10回 x 3セット | 中級",
    category: "上半身",
    duration: "20分",
    difficulty: "中級",
    imagePath: "assets/images/benchpress.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-lifting-weights-in-a-gym-42173-large.mp4",
    overview: "ベンチプレスは、大胸筋、上腕三頭筋、三角筋を鍛える、上半身トレーニングの代表的な種目です。（※要器具）",
    howTo: [
      "ベンチに仰向けになり、肩甲骨を寄せます。",
      "バーを肩幅よりやや広く握ります。",
      "バーをラックから外し、胸の一番高い位置までゆっくり下ろします。",
      "バーが胸につく直前で止め、息を吐きながら力強く持ち上げます。",
    ],
    tips: [
      "お尻は常にベンチにつけておきましょう。",
      "手首が反らないように、しっかりとバーを握ってください。",
    ],
    requiredAngle: "正面",
  ),
  TrainingMenu(
    id: "deadlift",
    title: "デッドリフト",
    description: "5回 x 3セット | 上級",
    category: "下半身",
    duration: "20分",
    difficulty: "上級",
    imagePath: "assets/images/deadlift.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-lifting-a-heavy-barbell-42168-large.mp4",
    overview: "デッドリフトは、背中、お尻、脚など、体の背面にあるほぼすべての筋肉を鍛えることができる種目です。（※要器具）",
    howTo: [
      "バーの前に立ち、足は腰幅程度に開きます。",
      "背筋をまっすぐにしたまま股関節から体を折り曲げ、バーを握ります。",
      "息を吸い込み、お腹に力を入れ、胸を張ります。",
      "床を足で押すイメージで、背筋をまっすぐに保ったまま立ち上がります。",
      "ゆっくりとバーを下ろします。",
    ],
    tips: [
      "動作中、背中が絶対に丸まらないようにしてください。",
      "バーは常に体の近くを通るように意識しましょう。",
    ],
    requiredAngle: "側面",
  ),
  TrainingMenu(
    id: "sideplank",
    title: "サイドプランク",
    description: "30秒 x 2セット | 中級",
    category: "コア",
    duration: "5分",
    difficulty: "中級",
    imagePath: "assets/images/sideplank.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-exercising-on-an-exercise-ball-42175-large.mp4",
    overview: "サイドプランクは、腹斜筋（脇腹）と体幹の安定性を鍛えるのに効果的なトレーニングです。",
    howTo: [
      "横向きになり、片方の肘を肩の真下に置きます。",
      "前腕と足の外側で体を支え、腰を持ち上げます。",
      "頭から足首までが一直線になるようにキープします。",
      "反対側も同様に行います。",
    ],
    tips: [
      "腰が落ちたり、お尻が後ろに引けたりしないように注意しましょう。",
      "上の手は腰に当てるか、天井に向かって伸ばします。",
    ],
    requiredAngle: "正面",
  ),
  TrainingMenu(
    id: "shoulderstretch",
    title: "肩のストレッチ",
    description: "30秒 x 2セット | 初級",
    category: "ヨガ",
    duration: "5分",
    difficulty: "初級",
    imagePath: "assets/images/shoulderstretch.jpg",
    isAsset: true,
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-woman-doing-yoga-in-the-living-room-12211-large.mp4",
    overview: "デスクワークやトレーニング後の肩の緊張をほぐし、柔軟性を高めるストレッチです。",
    howTo: [
      "立った状態、または座った状態で、片腕を胸の前にまっすぐ伸ばします。",
      "反対側の腕で、伸ばした腕の肘あたりを抱え、体に引き寄せます。",
      "肩が上がらないようにリラックスし、深い呼吸を続けます。",
      "反対側も同様に行います。",
    ],
    tips: [
      "痛みを感じない、「気持ちいい」と感じる範囲で伸ばしましょう。",
      "反動をつけずに、じわじわと伸ばしてください。",
    ],
    requiredAngle: "正面",
  ),
];

